#!/bin/bash

echo "Running pre-commit checks"

PROJECT_ROOT="$(git rev-parse --show-toplevel)"

bash "$PROJECT_ROOT/scripts/check-lint.sh"
if [ $? -ne 0 ]; then
    exit 1
fi

echo "✅ All pre-commit checks passed"
exit 0