services:
    formulix_app:
        image: node:20
        container_name: formulix_app
        command: npm run dev
        working_dir: /app
        ports:
            - ${APP_PORT}:5173
        volumes:
            - .:/app
