version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    working_dir: /app
    ports:
      - 8080:5173
    volumes:
      - .:/app
      - /app/node_modules
