version: "3"

services:
  app:
    image: node:19
    container_name: formulix-app
    command: npm start
    working_dir: /app
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
